name = "M_starpac"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2022, John S. Urban"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[[test]]
name="test_suite"
source-dir="test"
main="test_suite_M_starpac.f90"
[test.dependencies]
M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
