*CORRHD
      SUBROUTINE CORRHD(IPRT, M, N)
C
C     LATEST REVISION  -  03/15/90  (JRD)
C
C     A SUBROUTINE TO PRINT OUT THE HEADING FOR THE CORRELATION FAMILY.
C
C     AUTHOR -
C        JOHN E. KOONTZ
C        STATISTICAL ENGINEERING DIVISION
C        NATIONAL BUREAU OF STANDARDS, BOULDER, COLORADO
C
C     CREATION DATE  -  MAY 17, 1982
C
C
C  VARIABLE DECLARATIONS
C
C  SCALAR ARGUMENTS
      INTEGER
     +   IPRT,M,N
C
C  EXTERNAL SUBROUTINES
      EXTERNAL VERSP
C
C     VARIABLE DEFINITIONS (ALPHABETICALLY)
C
C     INTEGER IPRT
C        THE OUTPUT LOGICAL UNIT NUMBER
C     INTEGER M
C        THE NUMBER OF VARIABLES
C     INTEGER N
C        THE NUMBER OF OBSERVATIONS FOR EACH VARIABLE
C
      CALL VERSP(.TRUE.)
      WRITE (IPRT,1000) M, N
      RETURN
C
C     FORMAT STATEMENTS
C
 1000 FORMAT (/25H CORRELATION ANALYSIS FOR, I3, 15H VARIABLES WITH,
     +   I5, 13H OBSERVATIONS/)
      END
