*ECVF
      SUBROUTINE ECVF(NMSUB)
C
C     LATEST REVISION  -  03/15/90  (JRD)
C
C     THIS ROUTINE PRINTS AN ERROR MESSAGE WHEN THE LAG VALUE OF
C     THE LAST COVARIANCE COMPUTED BEFORE ONE WAS NOT COMPUTED
C     DUE TO MISSING DATA DOES NOT EXCEED ZERO.
C
C     WRITTEN BY  -  JANET R. DONALDSON
C                    STATISTICAL ENGINEERING DIVISION
C                    NATIONAL BUREAU OF STANDARDS, BOULDER, COLORADO
C
C     CREATION DATE  -  JUNE 10, 1982
C
C
C  VARIABLE DECLARATIONS
C
C  ARRAY ARGUMENTS
      CHARACTER
     +   NMSUB(6)*1
C
C  LOCAL SCALARS
      INTEGER
     +   IPRT
      LOGICAL
     +   HEAD
C
C  EXTERNAL SUBROUTINES
      EXTERNAL EHDR,IPRINT
C
C     VARIABLE DEFINITIONS (ALPHABETICALLY)
C
C     LOGICAL HEAD
C        A FLAG INDICATING WHETHER THE HEADING SHOULD BE PRINTED
C        (TRUE) OR NOT (FALSE).  IF A HEADING IS PRINTED, THE VALUE
C        OF HEAD WILL BE CHANGED TO FALSE.
C     INTEGER IPRT
C        THE LOGICAL UNIT USED FOR PRINTED OUTPUT.
C     CHARACTER*1 NMSUB(6)
C        THE ARRAY CONTAINING THE NAME OF THIS SUBROUTINE.
C
      CALL IPRINT(IPRT)
C
      HEAD = .TRUE.
C
      CALL EHDR(NMSUB, HEAD)
C
      WRITE(IPRT, 1010)
      RETURN
C
C     FORMAT STATEMENTS
C
 1010 FORMAT (/
     +   46H THE COVARIANCES AT LAGS ZERO AND/OR ONE COULD,
     +   16H NOT BE COMPUTED/
     +   49H BECAUSE OF MISSING DATA.  NO FURTHER ANALYSIS IS,
     +   10H POSSIBLE.)
C
      END
