*MSGX
      SUBROUTINE MSGX(IER, IPRT)
C
C     LATEST REVISION  -  03/15/90  (JRD)
C
C     THIS ROUTINE PRINTS THE RETURNED AND EXPECTED VALUES FOR THE
C     ERROR FLAG IERR
C
C     WRITTEN BY -
C        LINDA MITCHELL
C        STATISTICAL ENGINEERING DIVISION
C        NATIONAL BUREAU OF STANDARDS, BOULDER, COLORADO
C
C     CREATION DATE  -  MAY 17, 1982
C
C
C  VARIABLE DECLARATIONS
C
C  SCALAR ARGUMENTS
      INTEGER
     +   IER,IPRT
C
C  SCALARS IN COMMON
      INTEGER
     +   IERR
C
C  COMMON BLOCKS
      COMMON /ERRCHK/IERR
C
C     VARIBLE DEFINITIONS (ALPHABETICALLY)
C
C     INTEGER IER
C        EXPECTED VALUE OF ERROR FLAG IERR
C     INTEGER IERR
C        RETURNED ERROR FLAG FOUND IN THE COMMON ERRCHK
C     INTEGER IPRT
C        LOGICAL OUTPUT DEVICE
C
C
C     PRINT MESSAGE
      WRITE (IPRT,1000) IER, IERR
C
      IF (IER.NE.IERR) WRITE (IPRT,1010)
C
      RETURN
C
C     FORMAT STATEMENT
C
 1000 FORMAT(/28H EXPECTED VALUE FOR IERR IS , I1/15H RETURNED VALUE,
     +   12H FOR IERR IS, I2)
 1010 FORMAT(48H POSSIBLE ERROR, UNEXPECTED VALUE FOR ERROR FLAG)
      END
