*SETRA
      SUBROUTINE SETRA(ARRAY, IM, M, N, VALUE)
C
C     LATEST REVISION  -  03/15/90  (JRD)
C
C     SETS THE FIRST N ROWS AND M COLUMNS OF THE ARRAY
C
C     WRITTEN BY  -  LINDA L. MITCHELL
C                    STATISTICAL ENGINEERING DIVISION
C                    NATIONAL BUREAU OF STANDARDS, BOULDER, COLORADO
C
C     CREATION DATE  -  DECEMBER 7, 1981
C
C
C  VARIABLE DECLARATIONS
C
C  SCALAR ARGUMENTS
      DOUBLE PRECISION
     +   VALUE
      INTEGER
     +   IM,M,N
C
C  ARRAY ARGUMENTS
      DOUBLE PRECISION
     +   ARRAY(IM,M)
C
C  LOCAL SCALARS
      INTEGER
     +   I,J
C
C     VARIABLE DEFINITIONS (ALPHABETICALLY)
C
C     DOUBLE PRECISION ARRAY(IM,M)
C        ARRAY FOR WHICH ELEMENTS WILL BE SET
C     INTEGER I
C        *
C     INTEGER IM
C        ACTUAL FIRST DIMENSION OF ARRAY IN CALLING PROGRAM
C     INTEGER J
C        *
C     INTEGER M
C        NUMBER OF COLUMNS TO SET
C     INTEGER N
C        NUMBER OF ROWS TO SET
C     DOUBLE PRECISION VALUE
C        VALUE TO WHICH THE ELEMENTS ARE TO BE SET
C
C
      DO 20 I=1,N
         DO 10 J=1,M
            ARRAY(I,J) = VALUE
   10    CONTINUE
   20 CONTINUE
      RETURN
      END
