*CORRXP
      SUBROUTINE CORRXP(M, VCV, IVCV, IPRT)
C
C     LATEST REVISION  -  03/15/90  (JRD)
C
C     PRINT STORED OUTPUT RETURNED FROM CORRS
C
C     WRITTEN BY -
C        LINDA MITCHELL
C        STATISTICAL ENGINEERING DIVISION
C        NATIONAL BUREAU OF STANDARDS, BOULDER, COLORADO
C
C     CREATION DATE  -  MAY 17, 1982
C
C
C  VARIABLE DECLARATIONS
C
C  SCALAR ARGUMENTS
      INTEGER
     +   IPRT,IVCV,M
C
C  ARRAY ARGUMENTS
      REAL
     +   VCV(*)
C
C  EXTERNAL SUBROUTINES
      EXTERNAL MATPRT
C
C     VARIABLE DEFINITIONS (ALPHABETICALLY)
C
C     INTEGER IPRT
C        THE LOGICAL OUTPUT NUMBER
C     INTEGER IVCV
C        THE FIRST DIMENSION OF THE MATRIX VCV
C     INTEGER M
C        THE NUMBER OF VARIABLES IN THE ANALYSIS
C     REAL VCV(IVCV,M)
C        ARRAYS TO BE PRINTED
C
      IF (IVCV.GE.M) THEN
         WRITE (IPRT,1000)
         WRITE (IPRT,1010)
         CALL MATPRT(VCV, VCV, M, IPRT, 1, 1, IVCV)
      END IF
C
C     FORMAT STATEMENTS
C
      RETURN
 1000 FORMAT (/ 20H STORAGE FROM CORRS.)
 1010 FORMAT (40H STORAGE FROM VARIANCE-COVARIANCE MATRIX)
      END
