*NL2X
      SUBROUTINE NL2X
C     ***  TEST NL2SOL AND NL2SNO ON MADSEN EXAMPLE  ***
C
C  VARIABLE DECLARATIONS
C
C  LOCAL ARRAYS
      REAL
     +   URPARM(1),V(147),X(2)
      INTEGER
     +   IV(62),UIPARM(1)
C
C  EXTERNAL SUBROUTINES
      EXTERNAL MADJ,MADR,NL2SNO,NL2SOL,UFPARM
C
      X(1) = 3.0E0
      X(2) = 1.0E0
      IV(1) = 0
      CALL NL2SOL(3, 2, X, MADR, MADJ, IV, V, UIPARM, URPARM, UFPARM)
      IV(1) = 12
      X(1) = 3.0E0
      X(2) = 1.0E0
      CALL NL2SNO(3, 2, X, MADR, IV, V, UIPARM, URPARM, UFPARM)
      RETURN
      END
